title: card-city-content
context:
    cities:
        - title: ITALY
          subtitle: VENICE
          text: Venice, the capital of northern Italy's Veneto region, is built on more than 100 small islands in a lagoon in the Adriatic Sea. It has no roads, just canals.
        - title: GERMANY
          subtitle: BERLIN
          text: Berlin, Germany’s capital, dates to the 13th century. The city's known for its art scene and modern landmarks.
