describe('Viewport', () => {
  it('load the app in multiple viewports', () => {
    cy.visit('/')
    cy.wait(200)
    cy.viewport(360, 640)
    cy.wait(200)
    cy.viewport('iphone-6')
    cy.wait(200)
    cy.viewport('iphone-6+')
    cy.wait(200)
    cy.viewport('iphone-x')
    cy.wait(200)
    cy.viewport('iphone-xr')
    cy.wait(200)
    cy.viewport('samsung-note9')
    cy.wait(200)
    cy.viewport('samsung-s10')
    cy.wait(200)
    cy.viewport('ipad-2')
    cy.wait(200)
    cy.viewport(1024, 1366)
    cy.wait(200)
    cy.viewport('macbook-11')
    cy.wait(200)
    cy.viewport('macbook-13')
    cy.wait(200)
    cy.viewport('macbook-15')
  })
})
